### ISSUE TITLE
[0.6-1.4.0-rc] AppleSettings is not accessible in iosMain code

### ISSUE THREAD

**Issue by danielocampo2** [russhwolf/multiplatform-settings#55] opened 2020-07-31 19:30 UTC
Hi, 

I am using 0.6-1.4.0-rc with latest 1.4.0-rc Kotlin's version and while I am able to access the common Settings code (like Settings interface) from my iosMain shared code module, I can't seem to be able to access iOS related code like AppleSettings to use this factory. I get **UnresolvedReference** error.

I am just trying to do the following in iosMain/Whatever.kt
```AppleSettings.Factory().create("name.prefs")```

Was there any change for this version that I am missing?

Thanks.

**Comment by vanniktech** [comment] 2020-07-31 19:52
You need to expose it.

```
  targets.ios.binaries
      .findAll { it instanceof org.jetbrains.kotlin.gradle.plugin.mpp.Framework }
      .each {
        if (sdkName != null && sdkName.startsWith("iphoneos")) {
          it.export("com.russhwolf:multiplatform-settings-iosarm64:${versions.settings}")
        } else {
          it.export("com.russhwolf:multiplatform-settings-iosx64:${versions.settings}")
        }
      }
```

**Comment by danielocampo2** [comment] 2020-07-31 20:16
@vanniktech thanks for your answer. Correct me if I am wrong, but isn't that to be able to use Settings from Swift code? I need it to be used from Kotlin's MPP shared library (iosMain module).

I tried it anyway and wasn't successful.

This is how my build.gradle looks like:

```
import org.jetbrains.kotlin.gradle.tasks.KotlinCompile

val ktorVersion: String = "1.3.2-1.4.0-rc"
val kotlinVersion: String = "1.4.0-rc"
val coroutinesVersion = "1.3.8-native-mt-1.4.0-rc"
val serializationVersion = "0.20.0-1.4.0-rc"
val multiplatformSettingsVersion = "0.6-1.4.0-rc"
val kodeinVersion = "7.1.0-kotlin-1.4-rc-85"

plugins {
    kotlin("multiplatform")
    kotlin("native.cocoapods")
    id("kotlinx-serialization")
    id("com.android.library")
    id("io.fabric")
}

// CocoaPods requires the podspec to have a version.
version = "1.0"

tasks {
    withType<KotlinCompile> {
        kotlinOptions {
            jvmTarget = "1.8"
        }
    }
}

kotlin {
    ios()
    android()

    val iosArm64Target = targets.getByName("iosArm64") as org.jetbrains.kotlin.gradle.plugin.mpp.KotlinNativeTarget
    val iosX64Target = targets.getByName("iosX64") as org.jetbrains.kotlin.gradle.plugin.mpp.KotlinNativeTarget

    iosArm64Target.binaries.forEach {
        if (it is org.jetbrains.kotlin.gradle.plugin.mpp.Framework) {
            it.export("com.russhwolf:multiplatform-settings-iosarm64:$multiplatformSettingsVersion")
        }
    }

    iosX64Target.binaries.forEach {
        if (it is org.jetbrains.kotlin.gradle.plugin.mpp.Framework) {
            it.export("com.russhwolf:multiplatform-settings-iosx64:$multiplatformSettingsVersion")
        }
    }

    cocoapods {
        // Configure fields required by CocoaPods.
        summary = "Some description for a Kotlin/Native module"
        homepage = "Link to a Kotlin/Native module homepage"
    }

    sourceSets {
        val commonMain by getting {
            dependencies {
                implementation("org.jetbrains.kotlin:kotlin-stdlib-common")
                implementation("org.jetbrains.kotlinx:kotlinx-serialization-runtime:$serializationVersion")
                api("org.kodein.di:kodein-di:$kodeinVersion")
                implementation("io.mockk:mockk:1.9.2")

                api("org.jetbrains.kotlinx:kotlinx-coroutines-core:$coroutinesVersion")

                implementation("com.russhwolf:multiplatform-settings:$multiplatformSettingsVersion")

                implementation("io.ktor:ktor-client-core:$ktorVersion")
                implementation("io.ktor:ktor-client-json:$ktorVersion")
                implementation("io.ktor:ktor-client-logging:$ktorVersion")
                implementation("io.ktor:ktor-client-serialization:$ktorVersion")
            }
        }
       // .....
    }
}
```

**Comment by russhwolf** [comment] 2020-07-31 23:49
No deliberate changes that would lead to an error like that. You shouldn't need those iOS-specific exports if you don't need to access `AppleSettings` from Swift. Nothing in that build.gradle jumps out at me as an obvious cause for an issue like this, though there are some unrelated issues (mockk won't work on native, serialization 0.20.0-1.4.0-rc doesn't exist and should be 1.0-M1-1.4.0-rc)

Just in case, is it a build error or just an IDE error? ie can you build directly from gradle?

**Comment by danielocampo2** [comment] 2020-08-01 14:39
Hi @russhwolf , thanks for pointing that out. 

Seems to be only an IDE error actually, I was getting a build error from Xcode but it was the exported library code I added. After applying these changes the build works fine. 

Still would like to sort out the IDE issue as it is inconvenient but it is not a huge deal just yet. I am using the latest 1.4.0-rc Kotlin IDE plugin. 

Thanks again for your help and the library.

**Comment by russhwolf** [comment] 2020-08-01 15:22
Yeah, if it's just an IDE error it's extremely unlikely it's caused by this library, so I'm going to close this. 

Lots of subtle things can cause red code in the IDE. I've seen inconsistent behavior with the intermediate source-set created by the `ios()` builder your using, though setting `kotlin.mpp.enableGranularSourceSetsMetadata=true` in `gradle.properties` can sometimes help. I've also seen issues when a project's Kotlin version doesn't match the Kotlin IDE plugin version you have installed. I recommend reaching out on [Slack](https://kotlinlang.slack.com/) or [Youtrack](https://youtrack.jetbrains.com/issues/KT) for more help.

**Closed by russhwolf** 2020-08-01 15:22 UTC

**Comment by gchristov** [comment] 2021-04-07 15:11
Same thing happening for me - have added the dependency under `commonMain` and imported using `import com.russhwolf.settings.AppleSettings` resulting in the IDE showing the class not found. However, building and running the app works fine on both iOS and Android so not a huge issue but I wasted a bit of time trying to understand what I did wrong until I came across this issue.

**Comment by boldijar** [comment] 2021-08-18 16:21
> import com.russhwolf.settings.AppleSettings

No such module 'com.russhwolf.settings.AppleSettings'

For me it is still not working
