### ISSUE TITLE
Add Flow listeners for Serialized data

### ISSUE THREAD

**Issue by Vaibhav2002** [russhwolf/multiplatform-settings#208] opened 2024-10-21 08:38 UTC
Currently, there are flows for 
- getStringFlow()
- getLongFlow()

etc etc.

As Serialization support is now added a `settings.getSerializableFlow()` is needed

**Comment by russhwolf** [comment] 2024-11-01 02:08
Duplicate of #72

**Closed by russhwolf** 2024-11-01 02:08 UTC
