### ISSUE TITLE
Launching on devices stuck

### ISSUE THREAD

**Issue by a-samoha** [russhwolf/multiplatform-settings#210] opened 2024-10-29 19:06 UTC
Just added 
```kotlin
implementation("com.russhwolf:multiplatform-settings:1.2.0")
```
to commonMain dependencies and the `Launching on devices` process got stuck.

Build successfull, but it is impossible to install the debug version on the physical device.
Once got AS message "Unnknown error".
All other attempts was just the loading state until I broke it.

Device: `Samsung S21FE`

**Comment by russhwolf** [comment] 2024-11-01 02:10
Is this an issue with Multiplatform Settings or with Android Studio? I don't see anything I can do here without some sort of reproducer.

**Comment by russhwolf** [comment] 2024-11-16 22:53
Closing because I don't see what I can do that's helpful. Feel free to reopen if you can demonstrate a way to reproduce the error.

**Closed by russhwolf** 2024-11-16 22:53 UTC
