### ISSUE TITLE
SerializationApi has bug in iOS

### ISSUE THREAD

**Issue by abbasalim** [russhwolf/multiplatform-settings#174] opened 2023-11-14 07:41 UTC
Hi,
SerializationApi has bug in iOS, need to restart app to get new data.

**Comment by russhwolf** [comment] 2023-11-14 15:06
Can you give any more detail? This gives me nothing I can act on.

What does your code look like? What version are you using? What specifically are you trying to do, what do you expect to happen, and what happens instead?

**Comment by abbasalim** [comment] 2023-11-18 08:02
`multiplatformSettingsNoArg = "1.1.0"
multiplatformSettingsSerialization = "1.1.0"`

in the first screen of my app, we save user info if this is null, with :
`  fun setAuthUser(userModel: UserModel){
        settings.encodeValue(UserModel.serializer(), Keys.USER.value, userModel)
    }`

after in next screen we load data with : 
` fun user(): UserModel? {
        return settings.decodeValueOrNull(UserModel.serializer(),Keys.USER.value)
    }`

and show to user with 
`    val userName = mutableStateOf(authHelper.user()?.name)`

in android and desktop worked fine but in iOS
when saved data in first time, showed this when restart app

**Comment by russhwolf** [comment] 2024-05-20 22:47
Sorry this has been hanging for so long. Is this still an issue for you? The information you've given isn't enough for me to reproduce the problem.

**Comment by russhwolf** [comment] 2024-11-16 22:58
Closing because I can't reproduce the issue, but feel free to reopen if you're still having trouble

**Closed by russhwolf** 2024-11-16 22:58 UTC
